# Generated by Django 5.0.1 on 2024-02-05 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_alter_category_options_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='isSold',
            new_name='is_sold',
        ),
    ]
